server:
  port: 8443
  ssl:
    key-store: .keystore
    key-store-password: PUNKZEE
    key-store-type: JKS
    key-alias: tomcat
#spring:
#  mvc:
#    view:
#      prefix: classpath:/
#      suffix: .html